services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  roman-api:
    build: .
    container_name: roman-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - .env

volumes:
  pgdata: 
