name: github action # Name of the workflow

on: # Defines what will trigger the workflow
  push: # This will run the action whenever you push to the repo
    branches: # Makes sure the workflow runs whenever something is pushed to certain branches
      - master

permissions:
  contents: write

env:  # Workflow-wide variables
  PROJECT_ID: ae-terraform-2025
  REGION: europe-west4
  REPO_NAME: ae-2025-registry
  IMAGE_NAME: ad-image

jobs: # What should the workflow do?
  ci: # Name of the workflow
    runs-on: ubuntu-latest 
    steps:
      # Step 1: Clone the repository  
      - name: Repository checkout
        uses: actions/checkout@v3

      # Step 2: Install formatting and linting dependencies
      - name: Install formatting and linting dependencies
        run: |
          echo "Installing formatting and linting dependencies"
          pip install black ruff

      # Step 3: Run Python formatting (black)
      - name: Run Python formatting (black)
        run: |
          echo "Running black..."
          black .

      # Step 4: Run Python linting (ruff)
      - name: Run Python linting (flake8)
        run: |
          echo "Running flake8..."
          ruff check --fix .
      
      # Step 5: Configure git to allow merging
      - name: Configure git to allow merging
        run: |
          echo "Configuring git to allow merging"
          git config --global pull.rebase false

      # Step 6: Auto-commit changes
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format code with black and ruff"  
          # push: true  

      # Step 7: Testing
      - name: Run tests
        run: |
          echo "Running tests from test.py"
          pytest -v

      # Step 8: Authenticate with service account key
      - name: GCP authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'        

      # Step 9: Authenticate to configure docker
      - name: Docker configuration
        run: |
          echo "Configuring docker"
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet        

      # Step 10: Build and push the docker image
      - name: Docker Build and Push
        env: 
          IMAGE: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        run: |
          echo "Building image: $IMAGE"
          docker build -t $IMAGE .
          echo "Pusing image: $IMAGE"
          docker push $IMAGE

      # Step 11: Setting up Terraform
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1  # <-- match the version you want

      # Step 12: Initializing and planning Terrafrom
      - name: Terraform init and plan
        run: |
          echo "Initializing Terraform"
          terraform init
          echo "Planning Terraform"
          terraform plan


