name: github action # Name of the workflow

on: # Defines what will trigger the workflow
  push: # This will run the action whenever you push to the repo
    branches: # Makes sure the workflow runs whenever something is pushed to certain branches
      - master

env:  # Workflow-wide variables
  PROJECT_ID: ae-terraform-2025
  REGION: europe-west4
  REPO_NAME: ae-2025-registry
  IMAGE_NAME: ad-image

jobs: # What should the workflow do?
  ci: # Name of the workflow
    runs-on: ubuntu-latest 
    steps:
      # Step 1: Clone the repository  
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with service account key
      - name: GCP authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'        

      # Step 3: Authenticate to configure docker
      - name: Configuring docker
        run: |
          echo "Configuring docker"
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet        

      # Step 4: Build and push the docker image
      - name: Docker Build and Push
        env: 
          IMAGE: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        run: |
          echo "Building image: $IMAGE"
          docker build -t $IMAGE .
          echo "Pusing image: $IMAGE"
          docker push $IMAGE

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1  # <-- match the version you want

      # Step 6: Initializing and planning Terrafrom
      - name: Initializing and planning Terraform
        run: |
          echo "Initializing Terraform"
          terraform init
          echo "Planning Terraform"
          terraform plan


